#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai1_linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLLUONG")]
	public partial class QLLUONGDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchucvu(chucvu instance);
    partial void Updatechucvu(chucvu instance);
    partial void Deletechucvu(chucvu instance);
    partial void Insertdonvi(donvi instance);
    partial void Updatedonvi(donvi instance);
    partial void Deletedonvi(donvi instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    #endregion
		
		public QLLUONGDataContext() : 
				base(global::bai1_linq.Properties.Settings.Default.QLLUONGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLLUONGDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLLUONGDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLLUONGDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLLUONGDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chucvu> chucvus
		{
			get
			{
				return this.GetTable<chucvu>();
			}
		}
		
		public System.Data.Linq.Table<donvi> donvis
		{
			get
			{
				return this.GetTable<donvi>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chucvu")]
	public partial class chucvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _macv;
		
		private string _tencv;
		
		private double _phucap;
		
		private EntitySet<nhanvien> _nhanviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmacvChanging(string value);
    partial void OnmacvChanged();
    partial void OntencvChanging(string value);
    partial void OntencvChanged();
    partial void OnphucapChanging(double value);
    partial void OnphucapChanged();
    #endregion
		
		public chucvu()
		{
			this._nhanviens = new EntitySet<nhanvien>(new Action<nhanvien>(this.attach_nhanviens), new Action<nhanvien>(this.detach_nhanviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macv", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string macv
		{
			get
			{
				return this._macv;
			}
			set
			{
				if ((this._macv != value))
				{
					this.OnmacvChanging(value);
					this.SendPropertyChanging();
					this._macv = value;
					this.SendPropertyChanged("macv");
					this.OnmacvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tencv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tencv
		{
			get
			{
				return this._tencv;
			}
			set
			{
				if ((this._tencv != value))
				{
					this.OntencvChanging(value);
					this.SendPropertyChanging();
					this._tencv = value;
					this.SendPropertyChanged("tencv");
					this.OntencvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phucap", DbType="Float NOT NULL")]
		public double phucap
		{
			get
			{
				return this._phucap;
			}
			set
			{
				if ((this._phucap != value))
				{
					this.OnphucapChanging(value);
					this.SendPropertyChanging();
					this._phucap = value;
					this.SendPropertyChanged("phucap");
					this.OnphucapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chucvu_nhanvien", Storage="_nhanviens", ThisKey="macv", OtherKey="macv")]
		public EntitySet<nhanvien> nhanviens
		{
			get
			{
				return this._nhanviens;
			}
			set
			{
				this._nhanviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.chucvu = this;
		}
		
		private void detach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.chucvu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.donvi")]
	public partial class donvi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madv;
		
		private string _tendv;
		
		private string _dienthoai;
		
		private EntitySet<nhanvien> _nhanviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadvChanging(string value);
    partial void OnmadvChanged();
    partial void OntendvChanging(string value);
    partial void OntendvChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    #endregion
		
		public donvi()
		{
			this._nhanviens = new EntitySet<nhanvien>(new Action<nhanvien>(this.attach_nhanviens), new Action<nhanvien>(this.detach_nhanviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madv", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madv
		{
			get
			{
				return this._madv;
			}
			set
			{
				if ((this._madv != value))
				{
					this.OnmadvChanging(value);
					this.SendPropertyChanging();
					this._madv = value;
					this.SendPropertyChanged("madv");
					this.OnmadvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tendv
		{
			get
			{
				return this._tendv;
			}
			set
			{
				if ((this._tendv != value))
				{
					this.OntendvChanging(value);
					this.SendPropertyChanging();
					this._tendv = value;
					this.SendPropertyChanged("tendv");
					this.OntendvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donvi_nhanvien", Storage="_nhanviens", ThisKey="madv", OtherKey="madv")]
		public EntitySet<nhanvien> nhanviens
		{
			get
			{
				return this._nhanviens;
			}
			set
			{
				this._nhanviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.donvi = this;
		}
		
		private void detach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.donvi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manv;
		
		private string _hoten;
		
		private System.DateTime _ngaysinh;
		
		private double _hsluong;
		
		private string _trinhdo;
		
		private string _madv;
		
		private string _macv;
		
		private EntityRef<chucvu> _chucvu;
		
		private EntityRef<donvi> _donvi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.DateTime value);
    partial void OnngaysinhChanged();
    partial void OnhsluongChanging(double value);
    partial void OnhsluongChanged();
    partial void OntrinhdoChanging(string value);
    partial void OntrinhdoChanged();
    partial void OnmadvChanging(string value);
    partial void OnmadvChanged();
    partial void OnmacvChanging(string value);
    partial void OnmacvChanged();
    #endregion
		
		public nhanvien()
		{
			this._chucvu = default(EntityRef<chucvu>);
			this._donvi = default(EntityRef<donvi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hsluong", DbType="Float NOT NULL")]
		public double hsluong
		{
			get
			{
				return this._hsluong;
			}
			set
			{
				if ((this._hsluong != value))
				{
					this.OnhsluongChanging(value);
					this.SendPropertyChanging();
					this._hsluong = value;
					this.SendPropertyChanged("hsluong");
					this.OnhsluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trinhdo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trinhdo
		{
			get
			{
				return this._trinhdo;
			}
			set
			{
				if ((this._trinhdo != value))
				{
					this.OntrinhdoChanging(value);
					this.SendPropertyChanging();
					this._trinhdo = value;
					this.SendPropertyChanged("trinhdo");
					this.OntrinhdoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madv", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string madv
		{
			get
			{
				return this._madv;
			}
			set
			{
				if ((this._madv != value))
				{
					if (this._donvi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadvChanging(value);
					this.SendPropertyChanging();
					this._madv = value;
					this.SendPropertyChanged("madv");
					this.OnmadvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macv", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string macv
		{
			get
			{
				return this._macv;
			}
			set
			{
				if ((this._macv != value))
				{
					if (this._chucvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacvChanging(value);
					this.SendPropertyChanging();
					this._macv = value;
					this.SendPropertyChanged("macv");
					this.OnmacvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chucvu_nhanvien", Storage="_chucvu", ThisKey="macv", OtherKey="macv", IsForeignKey=true)]
		public chucvu chucvu
		{
			get
			{
				return this._chucvu.Entity;
			}
			set
			{
				chucvu previousValue = this._chucvu.Entity;
				if (((previousValue != value) 
							|| (this._chucvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chucvu.Entity = null;
						previousValue.nhanviens.Remove(this);
					}
					this._chucvu.Entity = value;
					if ((value != null))
					{
						value.nhanviens.Add(this);
						this._macv = value.macv;
					}
					else
					{
						this._macv = default(string);
					}
					this.SendPropertyChanged("chucvu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donvi_nhanvien", Storage="_donvi", ThisKey="madv", OtherKey="madv", IsForeignKey=true)]
		public donvi donvi
		{
			get
			{
				return this._donvi.Entity;
			}
			set
			{
				donvi previousValue = this._donvi.Entity;
				if (((previousValue != value) 
							|| (this._donvi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._donvi.Entity = null;
						previousValue.nhanviens.Remove(this);
					}
					this._donvi.Entity = value;
					if ((value != null))
					{
						value.nhanviens.Add(this);
						this._madv = value.madv;
					}
					else
					{
						this._madv = default(string);
					}
					this.SendPropertyChanged("donvi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
